# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171010_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
