# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_rating',
            field=models.IntegerField(default=0),
        ),
    ]
