# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20171008_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
