# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_whocomeonevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='boards.Post'),
            preserve_default=False,
        ),
    ]
