# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20171016_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
